### ISSUE TITLE
[Question] find() working for both language natural name and code

### ISSUE THREAD

**Issue by pettarin** [LuminosoInsight/langcodes#13]
If I understand correctly, currently there are two ways of getting a "language object": either through its code (``Language.get('eng')``), or via a search over its natural name (``langcodes.find('English')``).

However, e.g. ``langcodes.find('eng')`` returns a ``LookupError``.

What about providing a "unified" function that accepts either, first matching the code and then, if not found, performing the fuzzy search over the natural names?

This would remove the need for third party codes to (re)write such a function into each project. From experience, I know that user-facing code where a "language" parameter is expected will get values in both sets (natural names, codes), no matter how many times your documentation specifies that (say) codes should be provided...

For example, the following would return the same "language object":

```
langcodes.find('en')
langcodes.find('eng')
langcodes.find('English')
langcodes.find('english')
```

**Comment by rspeer** [comment]
I definitely understand the use case, and in fact I've encountered this kind of mixed data when parsing fr.wiktionary.org.

There are unfortunate edge cases. Should `langcodes.find('pal')` return:

* Pal, a language of Papua New Guinea with 1200 speakers, whose language code is `abw`?
* Or Middle Persian, otherwise known as Pahlavi, which has no extant speakers but a number of written documents, and whose language code is `pal`?

Another troubling example is "ron":

* The Ron language of Nigeria has 180,000 speakers.
* `ron` is listed in ISO 639-3 as the terminology language code for Romanian, even though I can find no trace of this in modern standards, which use `ro` or `rum`.

There are dozens of other examples, though many of them are for moribund languages that will probably never be represented on computers.

I was happy to reduce `langcodes.find()` to one argument by taking advantage of the fact that Unicode CLDR had eliminated all cross-lingual ambiguity from language names, and this reintroduces some. But if there's a justifiable thing we can do in the face of ambiguity, I'd be happy to implement it.

**Comment by pettarin** [comment]
Hi Rob, thank you for your detailed reply and for providing examples of the difficulties with the approach I proposed.

After your explanation, I think it makes sense not to change how ``find()`` function currently works.

Still, maybe a new function, performing the lookup of a given string over both codes and natural names, can be a way to address the use case. Perhaps this new function can return a list of matches, so that the caller can take action depending on whether the list she received back has zero length ("no match found"), one item ("got one language, yay!") or more ("warning! ambiguity!").

Assuming to call this new function "fuzzy_search()" (temporary name, I do not like it):

```
langcodes.fuzzy_search("asfdasdfassd") => []

langcodes.fuzzy_search("en") => [ ENG ]
langcodes.fuzzy_search("eng") => [ ENG ]
langcodes.fuzzy_search("English") => [ ENG ]
langcodes.fuzzy_search("english") => [ ENG ]

langcodes.fuzzy_search("pal") => [ PAL, ABW ]
```

In case of ambiguities, the returned list can be even refined depending on the query string:

```
# ISO code matching the query string first
langcodes.fuzzy_search("pal") => [ PAL, ABW ]

# probably they meant the language, put ABW first
langcodes.fuzzy_search("Pal") => [ ABW, PAL ]
langcodes.fuzzy_search("PAL") => [ ABW, PAL ]
```

(This "refined" reasoning might be questionable --- it should be checked against the actual ambiguous cases. just thinking aloud...)

**Comment by vorpalvorpal** [comment]
At the moment find(), but not get(), returns an error if unexpected content is found. Thus a simple work around for fuzzy search is:

`try:
    find('foo')
except:
    get('foo')`

In my current use case (where I am expecting language codes, but want to be able to cope if someone puts a language name in instead) it would make more sense to have the order of find and get reversed but get returns anything it doesn't recognise as if it were a valid language for some reason.

**Comment by rspeer** [comment]
After some thought, I don't want to do this. I'd prefer to keep names and codes distinct whenever possible. There are already too many cases where "codes as strings" can be confused with "codes as objects" in the code, and I don't want codes as strings to also be confused with "names as strings".
