### ISSUE TITLE
[Long shot] Decoupling the library code from the language db

### ISSUE THREAD

**Issue by pettarin** [LuminosoInsight/langcodes#14]
I was wondering whether there is a way of decoupling the code of langcodes from the actual language db, or, more precisely, to package langcodes with a subset of the language db.

My use case is the following: I want to have the machinery provided by langcodes (in particular, the fuzzy match of languages from a user-supplied string, and the hashable Language object), but on an extremely reduced subset of languages --- say only 100.

Currently, if I use langcodes in my application, I force the end-user to get 30+ MB of data from PyPI.

For example, for a project I am working on right now I coded this: https://github.com/pettarin/lachesis/blob/master/lachesis/language.py   but I would much much happier if I could use langcodes (sans 30+ MB of data) instead.

One way to achieve this could be the following:

1. add a "download" function to the package, able to fetch a language db from Internet;
2. add a "register" function to "add" the data for recognized languages;
3. put some logic in setup.py, so that:

```
pip install langcodes => install langcodes "code" and download all the CLDR data (e.g. from GitHub)
pip install langcodes[nodb] => install langcodes "code" but do not download all
```

In the second case, the client library/application would call the "register" function at runtime, providing the data for the recognized languages, (say) the subset of the CLDR of interest to that client.

**Comment by rspeer** [comment]
I'm interested in this too.

Some things that may help:

* The current language DB contains a lot of information that's used for prioritizing the best name for a code, or the best code for a name, and is never needed for any other purpose. If that prioritization happened in the build process, we could make a more compact data structure that only contains the data langcodes actually needs to run.

* Unicode CLDR v30 dropped support for a lot of languages that are not commonly used on computers, and we could follow suit. I know that I've never needed to know the word for any language in Tamazight, except possibly for "Tamazight". (Having a big list of autonyms can be nice for listing massively multilingual data, such as Wikipedia, but they can be special-cased.)

**Comment by rspeer** [comment]
Now I can't find the thing I saw about CLDR dropping a bunch of languages. I do see that the total number of translations keeps increasing, so we can't hope for CLDR to reduce the burden of data.

Another approach would be that we could have different data structures -- one for English, one for "common" languages, one for other languages, perhaps -- and as you suggest, these could be installed as optional dependencies.

**Comment by pettarin** [comment]
Rob, are you still interested in this? I can give it some serious thoughts if so.

**Comment by rspeer** [comment]
I am somewhat interested in this.

I believe that the big trie refactor that I just did should help reduce the "heaviness" of langcodes as a library. It now has only 7.4 MB of data, and doesn't require a database. But there's still more that could be done -- 6.5 MB of that is in the code-to-name trie, because that one still covers every CLDR language. There is probably room for a lighter version of it.

I definitely believe there could be an advantage to having one library for parsing and matching language tags (with no concept of what the things being matched are named), and another library for names.

That advantage might only be realized if the parsing-and-matching part is really fast -- perhaps if it's in a lower-level language than Python. On the side, I've been working on Rust code that matches language codes and is unconcerned with names. Maybe one day it could be packaged up and wrapped in Python. But this is mostly an excuse for me to practice programming in Rust and it may not amount to anything.

**Comment by goodmami** [comment]
> I definitely believe there could be an advantage to having one library for parsing and matching language tags (with no concept of what the things being matched are named), and another library for names.

I was about to open a new issue but this is exactly what I want. More specifically, I want to parse the tags to their components and get normalized tags. I'd also want it to (feature request) handle conversions of language codes, e.g., to get the ISO639-3 alpha-3 code even when there is an alpha-2 code. Without the language names, I don't think there's any need for a trie dependency, so we could sidestep or defer #35.

How would such a package look, do you think? Maybe this project does the above, and some `langnames` does the name matching? It could be an install extra (`pip install langcodes[names]`), and langcodes uses it if it's installed, otherwise raises an Error on some function calls.

**Comment by rspeer** [comment]
This does seem like an appropriate use case for the language names to be an optional feature. Time for me to start looking into this again.

**Comment by rspeer** [comment]
This is how langcodes 3.0 works now. Thanks for the suggestion.
