### ISSUE TITLE
remove .utf8

### ISSUE THREAD

**Issue by vorpalvorpal** [LuminosoInsight/langcodes#18]
os.getenv('LANG') returns (on my ubuntu system) a language code suffixed by .utf8. I would guess that other systems also do this. Would if be possible for langcodes.standardize_tags() to remove the .utf8 rather than throw an exception?

**Comment by rspeer** [comment]
Hmm. So in general, this is saying that `langcodes` should parse locale strings, right? If you're passing `os.getenv('LANG')` directly to it, then it needs to parse not just `en_US.utf8`, but also other things from outside the BCP 47 standard, like `en_US.utf8@modifier`, or `C.utf8`, or `POSIX`. (The last two of those should be parsed as if they were `und`, I guess, because they provide absolutely no BCP 47 information.)

It's certainly possible, but it might be something I don't want this library to get tangled up in. For one thing, is this really how to determine the system's configured language? There's LANG and a zillion `LC_*` environment variables, and any of them might be set or unset.

I've been hoping to keep langcodes as a clean way of referring to multilingual data, without reference to the multi-decade mess that locales are.
